name: harry_potter_example

description: "Aplicació d'exemple per provar layouts, localització, navegació i com controlar l'estat i persistir dades amb Flutter."

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.4.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true # l10n
