name: harry_potter_example

description: "Aplicació d'exemple per provar layouts i com funciona la navegació a Flutter."

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.4.3'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
