name: harry_potter_example

description: "Aplicaci贸 d'exemple per provar layouts, localitzaci贸, navegaci贸 i com controlar l'estat i persistir dades amb Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  package_rename: ^1.7.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true # l10n

package_rename_config:
  android:
    app_name: Hogwarts
    package_name: me.carleslc.hogwartsapp
    override_old_package: com.example.harry_potter_example
  ios:
    app_name: Hogwarts
    bundle_name: me.carleslc
    package_name: me.carleslc.hogwartsapp
  web:
    app_name: Hogwarts App
    short_app_name: Hogwarts
    description: Aplicaci贸 d'exemple amb Flutter, tematitzat amb Harry Potter.
